CREATE TABLE LEITOR 
(
  ID_LEITOR VARCHAR2(20 BYTE) NOT NULL 
, NOME_LEITOR VARCHAR2(50 BYTE) NOT NULL 
, ENDERECO_LEITOR VARCHAR2(70 BYTE) NOT NULL 
, CF_LEITOR VARCHAR2(20 BYTE) NOT NULL 
, TELEFONE_LEITOR VARCHAR2(20 BYTE) NOT NULL 
, CONSTRAINT LTEITOR_PK PRIMARY KEY 
  (
    ID_LEITOR 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX LTEITOR_PK ON LEITOR (ID_LEITOR ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
PARALLEL;
