/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Calculadora;

/**
 *
 * @author luciano.t.da.silva
 */
public class Inicial extends javax.swing.JFrame {

    /**
     * Creates new form Inicial
     */
    public Inicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TxtValor1 = new javax.swing.JTextField();
        TxtValor2 = new javax.swing.JTextField();
        BtnAdicao = new javax.swing.JButton();
        BtnMultiplicacao = new javax.swing.JButton();
        BtnSubtracao = new javax.swing.JButton();
        BtnDivisao = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        TxtResultado = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("1º Valor:");

        jLabel2.setText("2º Valor:");

        TxtValor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtValor1ActionPerformed(evt);
            }
        });

        TxtValor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtValor2ActionPerformed(evt);
            }
        });

        BtnAdicao.setText("Adição (+)");
        BtnAdicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAdicaoActionPerformed(evt);
            }
        });

        BtnMultiplicacao.setText("Multiplicação (*)");
        BtnMultiplicacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMultiplicacaoActionPerformed(evt);
            }
        });

        BtnSubtracao.setText("Subtração (-)");
        BtnSubtracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSubtracaoActionPerformed(evt);
            }
        });

        BtnDivisao.setText("Divisão (/)");
        BtnDivisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDivisaoActionPerformed(evt);
            }
        });

        jLabel3.setText("Resultado:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(TxtResultado))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(TxtValor2, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(TxtValor1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnMultiplicacao, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnAdicao, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnSubtracao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnDivisao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TxtValor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(TxtValor2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnAdicao)
                    .addComponent(BtnSubtracao))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnMultiplicacao)
                    .addComponent(BtnDivisao))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TxtResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtValor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtValor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtValor1ActionPerformed

    private void TxtValor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtValor2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtValor2ActionPerformed

    private void BtnAdicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAdicaoActionPerformed
        // TODO add your handling code here:
        
        int Valor1;
        int Valor2;
        
        int Resultado;
        
        Valor1 = Integer.parseInt(TxtValor1.getText());
        Valor2 = Integer.parseInt(TxtValor2.getText());
        
        Resultado = Valor1 + Valor2;
        
        TxtResultado.setText(Integer.toString(Resultado));
    }//GEN-LAST:event_BtnAdicaoActionPerformed

    private void BtnSubtracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSubtracaoActionPerformed
        // TODO add your handling code here:
        
        int Valor1;
        int Valor2;
        
        int Resultado;
        
        Valor1 = Integer.parseInt(TxtValor1.getText());
        Valor2 = Integer.parseInt(TxtValor2.getText());
        
        Resultado = Valor1 - Valor2;
        
        TxtResultado.setText(Integer.toString(Resultado));

    }//GEN-LAST:event_BtnSubtracaoActionPerformed

    private void BtnMultiplicacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMultiplicacaoActionPerformed
        // TODO add your handling code here:
        
        int Valor1;
        int Valor2;
        
        int Resultado;
        
        Valor1 = Integer.parseInt(TxtValor1.getText());
        Valor2 = Integer.parseInt(TxtValor2.getText());
        
        Resultado = Valor1 * Valor2;
        
        TxtResultado.setText(Integer.toString(Resultado));

    }//GEN-LAST:event_BtnMultiplicacaoActionPerformed

    private void BtnDivisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDivisaoActionPerformed
        // TODO add your handling code here:

        int Valor1;
        int Valor2;
        
        int Resultado;
        
        Valor1 = Integer.parseInt(TxtValor1.getText());
        Valor2 = Integer.parseInt(TxtValor2.getText());
        
        Resultado = Valor1 / Valor2;
        
        TxtResultado.setText(Integer.toString(Resultado));

    }//GEN-LAST:event_BtnDivisaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAdicao;
    private javax.swing.JButton BtnDivisao;
    private javax.swing.JButton BtnMultiplicacao;
    private javax.swing.JButton BtnSubtracao;
    private javax.swing.JTextField TxtResultado;
    private javax.swing.JTextField TxtValor1;
    private javax.swing.JTextField TxtValor2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
